### ISSUE TITLE
fixName leaving trailing [ for some items

### ISSUE THREAD

**Issue by Dromo** [LotroCompanion/lotro-core#10]
https://github.com/LotroCompanion/lotro-core/blob/1cd0255e1d56b9cdbf4cc97be4bff04204752366/src/main/java/delta/games/lotro/utils/StringUtils.java#L20

probably should use indexOf instead of lastIndexOf

Example: item id **1879269073** has name **Ceremonial Engraved Iron Gauntlets[[ps]** so currently the function produce **Ceremonial Engraved Iron Gauntlets[**

**Comment by dmorcellet** [comment]
Same issue with 1879359741 "Pony to the Party Tree["

**Comment by dmorcellet** [comment]
Also in a NPC name: 1879243909 "Ascbert["
The description of some items contains [...] blocks that shall be removed.

**Comment by dmorcellet** [comment]
Done.
